// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        data_V_V_dout,
        data_V_V_empty_n,
        data_V_V_read,
        res_V_V_din,
        res_V_V_full_n,
        res_V_V_write
);

parameter    ap_ST_fsm_state1 = 24'd1;
parameter    ap_ST_fsm_state2 = 24'd2;
parameter    ap_ST_fsm_state3 = 24'd4;
parameter    ap_ST_fsm_state4 = 24'd8;
parameter    ap_ST_fsm_pp0_stage0 = 24'd16;
parameter    ap_ST_fsm_state7 = 24'd32;
parameter    ap_ST_fsm_state8 = 24'd64;
parameter    ap_ST_fsm_state9 = 24'd128;
parameter    ap_ST_fsm_state10 = 24'd256;
parameter    ap_ST_fsm_state11 = 24'd512;
parameter    ap_ST_fsm_state12 = 24'd1024;
parameter    ap_ST_fsm_state13 = 24'd2048;
parameter    ap_ST_fsm_state14 = 24'd4096;
parameter    ap_ST_fsm_state15 = 24'd8192;
parameter    ap_ST_fsm_state16 = 24'd16384;
parameter    ap_ST_fsm_state17 = 24'd32768;
parameter    ap_ST_fsm_state18 = 24'd65536;
parameter    ap_ST_fsm_state19 = 24'd131072;
parameter    ap_ST_fsm_state20 = 24'd262144;
parameter    ap_ST_fsm_state21 = 24'd524288;
parameter    ap_ST_fsm_state22 = 24'd1048576;
parameter    ap_ST_fsm_state23 = 24'd2097152;
parameter    ap_ST_fsm_state24 = 24'd4194304;
parameter    ap_ST_fsm_state25 = 24'd8388608;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [17:0] data_V_V_dout;
input   data_V_V_empty_n;
output   data_V_V_read;
output  [17:0] res_V_V_din;
input   res_V_V_full_n;
output   res_V_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg data_V_V_read;
reg res_V_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [23:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [8:0] layer_in_V_5_address0;
reg    layer_in_V_5_ce0;
reg    layer_in_V_5_we0;
wire   [17:0] layer_in_V_5_q0;
reg   [31:0] sX;
reg   [31:0] sY;
reg   [31:0] pY;
reg   [31:0] pX;
wire   [8:0] w7_V_address0;
reg    w7_V_ce0;
wire   [446:0] w7_V_q0;
reg    data_V_V_blk_n;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln315_fu_1199_p2;
reg    res_V_V_blk_n;
wire    ap_CS_fsm_state24;
reg   [17:0] acc_V_31_0_reg_729;
reg   [17:0] acc_V_30_0_reg_742;
reg   [17:0] acc_V_29_0_reg_755;
reg   [17:0] acc_V_28_0_reg_768;
reg   [17:0] acc_V_27_0_reg_781;
reg   [17:0] acc_V_26_0_reg_794;
reg   [17:0] acc_V_25_0_reg_807;
reg   [17:0] acc_V_24_0_reg_820;
reg   [17:0] acc_V_23_0_reg_833;
reg   [17:0] acc_V_22_0_reg_846;
reg   [17:0] acc_V_21_0_reg_859;
reg   [17:0] acc_V_20_0_reg_872;
reg   [17:0] acc_V_19_0_reg_885;
reg   [17:0] acc_V_18_0_reg_898;
reg   [17:0] acc_V_17_0_reg_911;
reg   [17:0] acc_V_16_0_reg_924;
reg   [17:0] acc_V_15_0_reg_937;
reg   [17:0] acc_V_14_0_reg_950;
reg   [17:0] acc_V_13_0_reg_963;
reg   [17:0] acc_V_12_0_reg_976;
reg   [17:0] acc_V_11_0_reg_989;
reg   [17:0] acc_V_10_0_reg_1002;
reg   [17:0] acc_V_9_0_reg_1015;
reg   [17:0] acc_V_8_0_reg_1028;
reg   [17:0] acc_V_7_0_reg_1041;
reg   [17:0] acc_V_6_0_reg_1054;
reg   [17:0] acc_V_5_0_reg_1067;
reg   [17:0] acc_V_4_0_reg_1080;
reg   [17:0] acc_V_3_0_reg_1093;
reg   [17:0] acc_V_2_0_reg_1106;
reg   [17:0] acc_V_1_0_reg_1119;
reg   [17:0] acc_V_0_0_reg_1132;
reg   [8:0] in_index_reg_1145;
reg    ap_block_state1;
wire   [10:0] i_fu_1193_p2;
reg   [10:0] i_reg_2728;
wire    ap_CS_fsm_state2;
wire   [5:0] i1_fu_1205_p2;
reg    ap_block_state3;
reg   [31:0] sX_load_reg_2741;
wire    ap_CS_fsm_state4;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_ready;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done;
wire   [0:0] icmp_ln326_fu_1220_p2;
reg   [0:0] icmp_ln326_reg_2746;
reg   [31:0] sY_load_reg_2751;
wire   [0:0] icmp_ln326_1_fu_1230_p2;
reg   [0:0] icmp_ln326_1_reg_2756;
reg   [31:0] pY_load_reg_2761;
reg   [31:0] pX_load_reg_2767;
wire   [0:0] and_ln326_2_fu_1288_p2;
reg   [0:0] and_ln326_2_reg_2773;
wire   [0:0] icmp_ln324_fu_1294_p2;
reg   [0:0] icmp_ln324_reg_2777;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [8:0] ir_fu_1300_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [17:0] acc_0_V_fu_2046_p2;
reg    ap_enable_reg_pp0_iter1;
wire   [17:0] acc_1_V_fu_2052_p2;
wire   [17:0] acc_2_V_fu_2058_p2;
wire   [17:0] acc_3_V_fu_2064_p2;
wire   [17:0] acc_4_V_fu_2070_p2;
wire   [17:0] acc_5_V_fu_2076_p2;
wire   [17:0] acc_6_V_fu_2082_p2;
wire   [17:0] acc_7_V_fu_2088_p2;
wire   [17:0] acc_8_V_fu_2094_p2;
wire   [17:0] acc_9_V_fu_2100_p2;
wire   [17:0] acc_10_V_fu_2106_p2;
wire   [17:0] acc_11_V_fu_2112_p2;
wire   [17:0] acc_12_V_fu_2118_p2;
wire   [17:0] acc_13_V_fu_2124_p2;
wire   [17:0] acc_14_V_fu_2130_p2;
wire   [17:0] acc_15_V_fu_2136_p2;
wire   [17:0] acc_16_V_fu_2142_p2;
wire   [17:0] acc_17_V_fu_2148_p2;
wire   [17:0] acc_18_V_fu_2154_p2;
wire   [17:0] acc_19_V_fu_2160_p2;
wire   [17:0] acc_20_V_fu_2166_p2;
wire   [17:0] acc_21_V_fu_2172_p2;
wire   [17:0] acc_22_V_fu_2178_p2;
wire   [17:0] acc_23_V_fu_2184_p2;
wire   [17:0] acc_24_V_fu_2190_p2;
wire   [17:0] acc_25_V_fu_2196_p2;
wire   [17:0] acc_26_V_fu_2202_p2;
wire   [17:0] acc_27_V_fu_2208_p2;
wire   [17:0] acc_28_V_fu_2214_p2;
wire   [17:0] acc_29_V_fu_2220_p2;
wire   [17:0] acc_30_V_fu_2226_p2;
wire   [17:0] acc_31_V_fu_2232_p2;
wire   [5:0] i_ic_fu_2244_p2;
reg   [5:0] i_ic_reg_2959;
wire    ap_CS_fsm_state23;
wire   [0:0] icmp_ln338_fu_2238_p2;
wire   [0:0] icmp_ln346_fu_2255_p2;
reg   [0:0] icmp_ln346_reg_2969;
wire   [31:0] select_ln356_fu_2322_p3;
wire   [0:0] icmp_ln350_fu_2301_p2;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state5;
reg   [4:0] tmpdata_V_address0;
reg    tmpdata_V_ce0;
reg    tmpdata_V_we0;
wire   [17:0] tmpdata_V_q0;
reg   [4:0] layer_out_i_address0;
reg    layer_out_i_ce0;
reg    layer_out_i_we0;
reg   [17:0] layer_out_i_d0;
wire   [17:0] layer_out_i_q0;
reg   [4:0] layer_out_i_address1;
reg    layer_out_i_ce1;
reg    layer_out_i_we1;
reg   [17:0] layer_out_i_d1;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_start;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_idle;
wire   [4:0] grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_data_V_address0;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_data_V_ce0;
wire   [8:0] grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_output_V_address0;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_output_V_ce0;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_output_V_we0;
wire   [17:0] grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_output_V_d0;
reg   [10:0] i_0_i_reg_707;
wire    ap_CS_fsm_state25;
reg   [5:0] i1_0_i_reg_718;
wire   [0:0] icmp_ln313_fu_1187_p2;
wire    ap_block_pp0_stage0;
reg   [5:0] i_ic_0_i_reg_1156;
wire    ap_CS_fsm_state22;
reg   [31:0] storemerge_i_reg_1167;
reg    grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_start_reg;
reg    ap_block_state3_ignore_call0;
wire   [63:0] zext_ln317_fu_1211_p1;
wire   [63:0] zext_ln332_fu_1306_p1;
wire   [63:0] zext_ln340_fu_2250_p1;
wire   [31:0] select_ln361_fu_2276_p3;
wire   [31:0] add_ln354_fu_2306_p2;
wire   [31:0] add_ln359_fu_2260_p2;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire   [30:0] tmp_3_fu_1240_p4;
wire   [30:0] tmp_4_fu_1260_p4;
wire   [0:0] icmp_ln326_2_fu_1250_p2;
wire   [0:0] icmp_ln326_3_fu_1270_p2;
wire   [0:0] and_ln326_1_fu_1282_p2;
wire   [0:0] and_ln326_fu_1276_p2;
wire  signed [13:0] trunc_ln332_fu_1312_p1;
wire  signed [28:0] mul_ln1118_fu_2341_p2;
wire  signed [13:0] tmp_48_fu_1333_p4;
wire  signed [28:0] mul_ln1118_5_fu_2348_p2;
wire  signed [13:0] tmp_49_fu_1356_p4;
wire  signed [28:0] mul_ln1118_6_fu_2355_p2;
wire  signed [13:0] tmp_50_fu_1379_p4;
wire  signed [28:0] mul_ln1118_7_fu_2362_p2;
wire  signed [13:0] tmp_51_fu_1402_p4;
wire  signed [28:0] mul_ln1118_8_fu_2369_p2;
wire  signed [13:0] tmp_52_fu_1425_p4;
wire  signed [28:0] mul_ln1118_9_fu_2376_p2;
wire  signed [13:0] tmp_53_fu_1448_p4;
wire  signed [28:0] mul_ln1118_10_fu_2383_p2;
wire  signed [13:0] tmp_54_fu_1471_p4;
wire  signed [28:0] mul_ln1118_11_fu_2390_p2;
wire  signed [13:0] tmp_55_fu_1494_p4;
wire  signed [28:0] mul_ln1118_12_fu_2397_p2;
wire  signed [13:0] tmp_56_fu_1517_p4;
wire  signed [28:0] mul_ln1118_13_fu_2404_p2;
wire  signed [13:0] tmp_57_fu_1540_p4;
wire  signed [28:0] mul_ln1118_14_fu_2411_p2;
wire  signed [13:0] tmp_58_fu_1563_p4;
wire  signed [28:0] mul_ln1118_15_fu_2418_p2;
wire  signed [13:0] tmp_59_fu_1586_p4;
wire  signed [28:0] mul_ln1118_16_fu_2425_p2;
wire  signed [13:0] tmp_60_fu_1609_p4;
wire  signed [28:0] mul_ln1118_17_fu_2432_p2;
wire  signed [13:0] tmp_61_fu_1632_p4;
wire  signed [28:0] mul_ln1118_18_fu_2439_p2;
wire  signed [13:0] tmp_62_fu_1655_p4;
wire  signed [28:0] mul_ln1118_19_fu_2446_p2;
wire  signed [13:0] tmp_63_fu_1678_p4;
wire  signed [28:0] mul_ln1118_20_fu_2453_p2;
wire  signed [13:0] tmp_64_fu_1701_p4;
wire  signed [28:0] mul_ln1118_21_fu_2460_p2;
wire  signed [13:0] tmp_65_fu_1724_p4;
wire  signed [28:0] mul_ln1118_22_fu_2467_p2;
wire  signed [13:0] tmp_66_fu_1747_p4;
wire  signed [28:0] mul_ln1118_23_fu_2474_p2;
wire  signed [13:0] tmp_67_fu_1770_p4;
wire  signed [28:0] mul_ln1118_24_fu_2481_p2;
wire  signed [13:0] tmp_68_fu_1793_p4;
wire  signed [28:0] mul_ln1118_25_fu_2488_p2;
wire  signed [13:0] tmp_69_fu_1816_p4;
wire  signed [28:0] mul_ln1118_26_fu_2495_p2;
wire  signed [13:0] tmp_70_fu_1839_p4;
wire  signed [28:0] mul_ln1118_27_fu_2502_p2;
wire  signed [13:0] tmp_71_fu_1862_p4;
wire  signed [28:0] mul_ln1118_28_fu_2509_p2;
wire  signed [13:0] tmp_72_fu_1885_p4;
wire  signed [28:0] mul_ln1118_29_fu_2516_p2;
wire  signed [13:0] tmp_73_fu_1908_p4;
wire  signed [28:0] mul_ln1118_30_fu_2523_p2;
wire  signed [13:0] tmp_74_fu_1931_p4;
wire  signed [28:0] mul_ln1118_31_fu_2530_p2;
wire  signed [13:0] tmp_75_fu_1954_p4;
wire  signed [28:0] mul_ln1118_32_fu_2537_p2;
wire  signed [13:0] tmp_76_fu_1977_p4;
wire  signed [28:0] mul_ln1118_33_fu_2544_p2;
wire  signed [13:0] tmp_77_fu_2000_p4;
wire  signed [28:0] mul_ln1118_34_fu_2551_p2;
wire  signed [12:0] tmp_2_fu_2023_p4;
wire  signed [28:0] mul_ln1118_35_fu_2558_p2;
wire   [17:0] trunc_ln_fu_1324_p4;
wire   [17:0] trunc_ln708_5_fu_1347_p4;
wire   [17:0] trunc_ln708_6_fu_1370_p4;
wire   [17:0] trunc_ln708_7_fu_1393_p4;
wire   [17:0] trunc_ln708_8_fu_1416_p4;
wire   [17:0] trunc_ln708_9_fu_1439_p4;
wire   [17:0] trunc_ln708_s_fu_1462_p4;
wire   [17:0] trunc_ln708_1_fu_1485_p4;
wire   [17:0] trunc_ln708_2_fu_1508_p4;
wire   [17:0] trunc_ln708_3_fu_1531_p4;
wire   [17:0] trunc_ln708_4_fu_1554_p4;
wire   [17:0] trunc_ln708_10_fu_1577_p4;
wire   [17:0] trunc_ln708_11_fu_1600_p4;
wire   [17:0] trunc_ln708_12_fu_1623_p4;
wire   [17:0] trunc_ln708_13_fu_1646_p4;
wire   [17:0] trunc_ln708_14_fu_1669_p4;
wire   [17:0] trunc_ln708_15_fu_1692_p4;
wire   [17:0] trunc_ln708_16_fu_1715_p4;
wire   [17:0] trunc_ln708_17_fu_1738_p4;
wire   [17:0] trunc_ln708_18_fu_1761_p4;
wire   [17:0] trunc_ln708_19_fu_1784_p4;
wire   [17:0] trunc_ln708_20_fu_1807_p4;
wire   [17:0] trunc_ln708_21_fu_1830_p4;
wire   [17:0] trunc_ln708_22_fu_1853_p4;
wire   [17:0] trunc_ln708_23_fu_1876_p4;
wire   [17:0] trunc_ln708_24_fu_1899_p4;
wire   [17:0] trunc_ln708_25_fu_1922_p4;
wire   [17:0] trunc_ln708_26_fu_1945_p4;
wire   [17:0] trunc_ln708_27_fu_1968_p4;
wire   [17:0] trunc_ln708_28_fu_1991_p4;
wire   [17:0] trunc_ln708_29_fu_2014_p4;
wire   [17:0] trunc_ln708_30_fu_2037_p4;
wire   [31:0] add_ln361_fu_2271_p2;
wire   [31:0] add_ln356_fu_2317_p2;
wire  signed [17:0] mul_ln1118_fu_2341_p1;
wire  signed [28:0] sext_ln1116_cast_fu_1316_p1;
wire  signed [17:0] mul_ln1118_5_fu_2348_p1;
wire  signed [17:0] mul_ln1118_6_fu_2355_p1;
wire  signed [17:0] mul_ln1118_7_fu_2362_p1;
wire  signed [17:0] mul_ln1118_8_fu_2369_p1;
wire  signed [17:0] mul_ln1118_9_fu_2376_p1;
wire  signed [17:0] mul_ln1118_10_fu_2383_p1;
wire  signed [17:0] mul_ln1118_11_fu_2390_p1;
wire  signed [17:0] mul_ln1118_12_fu_2397_p1;
wire  signed [17:0] mul_ln1118_13_fu_2404_p1;
wire  signed [17:0] mul_ln1118_14_fu_2411_p1;
wire  signed [17:0] mul_ln1118_15_fu_2418_p1;
wire  signed [17:0] mul_ln1118_16_fu_2425_p1;
wire  signed [17:0] mul_ln1118_17_fu_2432_p1;
wire  signed [17:0] mul_ln1118_18_fu_2439_p1;
wire  signed [17:0] mul_ln1118_19_fu_2446_p1;
wire  signed [17:0] mul_ln1118_20_fu_2453_p1;
wire  signed [17:0] mul_ln1118_21_fu_2460_p1;
wire  signed [17:0] mul_ln1118_22_fu_2467_p1;
wire  signed [17:0] mul_ln1118_23_fu_2474_p1;
wire  signed [17:0] mul_ln1118_24_fu_2481_p1;
wire  signed [17:0] mul_ln1118_25_fu_2488_p1;
wire  signed [17:0] mul_ln1118_26_fu_2495_p1;
wire  signed [17:0] mul_ln1118_27_fu_2502_p1;
wire  signed [17:0] mul_ln1118_28_fu_2509_p1;
wire  signed [17:0] mul_ln1118_29_fu_2516_p1;
wire  signed [17:0] mul_ln1118_30_fu_2523_p1;
wire  signed [17:0] mul_ln1118_31_fu_2530_p1;
wire  signed [17:0] mul_ln1118_32_fu_2537_p1;
wire  signed [17:0] mul_ln1118_33_fu_2544_p1;
wire  signed [17:0] mul_ln1118_34_fu_2551_p1;
wire  signed [17:0] mul_ln1118_35_fu_2558_p1;
reg   [23:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_618;
reg    ap_condition_620;
reg    ap_condition_405;
reg    ap_condition_556;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 24'd1;
#0 sX = 32'd0;
#0 sY = 32'd0;
#0 pY = 32'd0;
#0 pX = 32'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_start_reg = 1'b0;
end

conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_layeibs #(
    .DataWidth( 18 ),
    .AddressRange( 288 ),
    .AddressWidth( 9 ))
layer_in_V_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer_in_V_5_address0),
    .ce0(layer_in_V_5_ce0),
    .we0(layer_in_V_5_we0),
    .d0(grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_output_V_d0),
    .q0(layer_in_V_5_q0)
);

conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_w7_V #(
    .DataWidth( 447 ),
    .AddressRange( 288 ),
    .AddressWidth( 9 ))
w7_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w7_V_address0),
    .ce0(w7_V_ce0),
    .q0(w7_V_q0)
);

conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_tmpdjbC #(
    .DataWidth( 18 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
tmpdata_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmpdata_V_address0),
    .ce0(tmpdata_V_ce0),
    .we0(tmpdata_V_we0),
    .d0(data_V_V_dout),
    .q0(tmpdata_V_q0)
);

conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_s_layefYi #(
    .DataWidth( 18 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
layer_out_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer_out_i_address0),
    .ce0(layer_out_i_ce0),
    .we0(layer_out_i_we0),
    .d0(layer_out_i_d0),
    .q0(layer_out_i_q0),
    .address1(layer_out_i_address1),
    .ce1(layer_out_i_ce1),
    .we1(layer_out_i_we1),
    .d1(layer_out_i_d1)
);

cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_start),
    .ap_done(grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done),
    .ap_idle(grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_idle),
    .ap_ready(grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_ready),
    .data_V_address0(grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_data_V_address0),
    .data_V_ce0(grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_data_V_ce0),
    .data_V_q0(tmpdata_V_q0),
    .output_V_address0(grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_output_V_address0),
    .output_V_ce0(grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_output_V_ce0),
    .output_V_we0(grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_output_V_we0),
    .output_V_d0(grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_output_V_d0),
    .output_V_q0(layer_in_V_5_q0)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U56(
    .din0(trunc_ln332_fu_1312_p1),
    .din1(mul_ln1118_fu_2341_p1),
    .dout(mul_ln1118_fu_2341_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U57(
    .din0(tmp_48_fu_1333_p4),
    .din1(mul_ln1118_5_fu_2348_p1),
    .dout(mul_ln1118_5_fu_2348_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U58(
    .din0(tmp_49_fu_1356_p4),
    .din1(mul_ln1118_6_fu_2355_p1),
    .dout(mul_ln1118_6_fu_2355_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U59(
    .din0(tmp_50_fu_1379_p4),
    .din1(mul_ln1118_7_fu_2362_p1),
    .dout(mul_ln1118_7_fu_2362_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U60(
    .din0(tmp_51_fu_1402_p4),
    .din1(mul_ln1118_8_fu_2369_p1),
    .dout(mul_ln1118_8_fu_2369_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U61(
    .din0(tmp_52_fu_1425_p4),
    .din1(mul_ln1118_9_fu_2376_p1),
    .dout(mul_ln1118_9_fu_2376_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U62(
    .din0(tmp_53_fu_1448_p4),
    .din1(mul_ln1118_10_fu_2383_p1),
    .dout(mul_ln1118_10_fu_2383_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U63(
    .din0(tmp_54_fu_1471_p4),
    .din1(mul_ln1118_11_fu_2390_p1),
    .dout(mul_ln1118_11_fu_2390_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U64(
    .din0(tmp_55_fu_1494_p4),
    .din1(mul_ln1118_12_fu_2397_p1),
    .dout(mul_ln1118_12_fu_2397_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U65(
    .din0(tmp_56_fu_1517_p4),
    .din1(mul_ln1118_13_fu_2404_p1),
    .dout(mul_ln1118_13_fu_2404_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U66(
    .din0(tmp_57_fu_1540_p4),
    .din1(mul_ln1118_14_fu_2411_p1),
    .dout(mul_ln1118_14_fu_2411_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U67(
    .din0(tmp_58_fu_1563_p4),
    .din1(mul_ln1118_15_fu_2418_p1),
    .dout(mul_ln1118_15_fu_2418_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U68(
    .din0(tmp_59_fu_1586_p4),
    .din1(mul_ln1118_16_fu_2425_p1),
    .dout(mul_ln1118_16_fu_2425_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U69(
    .din0(tmp_60_fu_1609_p4),
    .din1(mul_ln1118_17_fu_2432_p1),
    .dout(mul_ln1118_17_fu_2432_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U70(
    .din0(tmp_61_fu_1632_p4),
    .din1(mul_ln1118_18_fu_2439_p1),
    .dout(mul_ln1118_18_fu_2439_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U71(
    .din0(tmp_62_fu_1655_p4),
    .din1(mul_ln1118_19_fu_2446_p1),
    .dout(mul_ln1118_19_fu_2446_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U72(
    .din0(tmp_63_fu_1678_p4),
    .din1(mul_ln1118_20_fu_2453_p1),
    .dout(mul_ln1118_20_fu_2453_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U73(
    .din0(tmp_64_fu_1701_p4),
    .din1(mul_ln1118_21_fu_2460_p1),
    .dout(mul_ln1118_21_fu_2460_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U74(
    .din0(tmp_65_fu_1724_p4),
    .din1(mul_ln1118_22_fu_2467_p1),
    .dout(mul_ln1118_22_fu_2467_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U75(
    .din0(tmp_66_fu_1747_p4),
    .din1(mul_ln1118_23_fu_2474_p1),
    .dout(mul_ln1118_23_fu_2474_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U76(
    .din0(tmp_67_fu_1770_p4),
    .din1(mul_ln1118_24_fu_2481_p1),
    .dout(mul_ln1118_24_fu_2481_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U77(
    .din0(tmp_68_fu_1793_p4),
    .din1(mul_ln1118_25_fu_2488_p1),
    .dout(mul_ln1118_25_fu_2488_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U78(
    .din0(tmp_69_fu_1816_p4),
    .din1(mul_ln1118_26_fu_2495_p1),
    .dout(mul_ln1118_26_fu_2495_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U79(
    .din0(tmp_70_fu_1839_p4),
    .din1(mul_ln1118_27_fu_2502_p1),
    .dout(mul_ln1118_27_fu_2502_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U80(
    .din0(tmp_71_fu_1862_p4),
    .din1(mul_ln1118_28_fu_2509_p1),
    .dout(mul_ln1118_28_fu_2509_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U81(
    .din0(tmp_72_fu_1885_p4),
    .din1(mul_ln1118_29_fu_2516_p1),
    .dout(mul_ln1118_29_fu_2516_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U82(
    .din0(tmp_73_fu_1908_p4),
    .din1(mul_ln1118_30_fu_2523_p1),
    .dout(mul_ln1118_30_fu_2523_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U83(
    .din0(tmp_74_fu_1931_p4),
    .din1(mul_ln1118_31_fu_2530_p1),
    .dout(mul_ln1118_31_fu_2530_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U84(
    .din0(tmp_75_fu_1954_p4),
    .din1(mul_ln1118_32_fu_2537_p1),
    .dout(mul_ln1118_32_fu_2537_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U85(
    .din0(tmp_76_fu_1977_p4),
    .din1(mul_ln1118_33_fu_2544_p1),
    .dout(mul_ln1118_33_fu_2544_p2)
);

myproject_mul_mul_14s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_14s_18s_29_1_1_U86(
    .din0(tmp_77_fu_2000_p4),
    .din1(mul_ln1118_34_fu_2551_p1),
    .dout(mul_ln1118_34_fu_2551_p2)
);

myproject_mul_mul_13s_18s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 29 ))
myproject_mul_mul_13s_18s_29_1_1_U87(
    .din0(tmp_2_fu_2023_p4),
    .din1(mul_ln1118_35_fu_2558_p1),
    .dout(mul_ln1118_35_fu_2558_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln313_fu_1187_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state5) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state5))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state5);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_start_reg <= 1'b0;
    end else begin
        if ((~((icmp_ln315_fu_1199_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1199_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_start_reg <= 1'b1;
        end else if ((grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_ready == 1'b1)) begin
            grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_0_0_reg_1132 <= acc_0_V_fu_2046_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_0_0_reg_1132 <= 18'd262018;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_10_0_reg_1002 <= acc_10_V_fu_2106_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_10_0_reg_1002 <= 18'd262029;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_11_0_reg_989 <= acc_11_V_fu_2112_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_11_0_reg_989 <= 18'd261967;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_12_0_reg_976 <= acc_12_V_fu_2118_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_12_0_reg_976 <= 18'd31;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_13_0_reg_963 <= acc_13_V_fu_2124_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_13_0_reg_963 <= 18'd14;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_14_0_reg_950 <= acc_14_V_fu_2130_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_14_0_reg_950 <= 18'd262124;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_15_0_reg_937 <= acc_15_V_fu_2136_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_15_0_reg_937 <= 18'd261684;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_16_0_reg_924 <= acc_16_V_fu_2142_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_16_0_reg_924 <= 18'd116;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_17_0_reg_911 <= acc_17_V_fu_2148_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_17_0_reg_911 <= 18'd262121;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_18_0_reg_898 <= acc_18_V_fu_2154_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_18_0_reg_898 <= 18'd262057;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_19_0_reg_885 <= acc_19_V_fu_2160_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_19_0_reg_885 <= 18'd98;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_1_0_reg_1119 <= acc_1_V_fu_2052_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_1_0_reg_1119 <= 18'd261898;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_20_0_reg_872 <= acc_20_V_fu_2166_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_20_0_reg_872 <= 18'd261998;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_21_0_reg_859 <= acc_21_V_fu_2172_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_21_0_reg_859 <= 18'd261927;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_22_0_reg_846 <= acc_22_V_fu_2178_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_22_0_reg_846 <= 18'd262029;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_23_0_reg_833 <= acc_23_V_fu_2184_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_23_0_reg_833 <= 18'd262045;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_24_0_reg_820 <= acc_24_V_fu_2190_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_24_0_reg_820 <= 18'd29;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_25_0_reg_807 <= acc_25_V_fu_2196_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_25_0_reg_807 <= 18'd261984;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_26_0_reg_794 <= acc_26_V_fu_2202_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_26_0_reg_794 <= 18'd261959;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_27_0_reg_781 <= acc_27_V_fu_2208_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_27_0_reg_781 <= 18'd262087;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_28_0_reg_768 <= acc_28_V_fu_2214_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_28_0_reg_768 <= 18'd262006;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_29_0_reg_755 <= acc_29_V_fu_2220_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_29_0_reg_755 <= 18'd112;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_2_0_reg_1106 <= acc_2_V_fu_2058_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_2_0_reg_1106 <= 18'd262025;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_30_0_reg_742 <= acc_30_V_fu_2226_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_30_0_reg_742 <= 18'd262009;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_31_0_reg_729 <= acc_31_V_fu_2232_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_31_0_reg_729 <= 18'd38;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_3_0_reg_1093 <= acc_3_V_fu_2064_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_3_0_reg_1093 <= 18'd2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_4_0_reg_1080 <= acc_4_V_fu_2070_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_4_0_reg_1080 <= 18'd261928;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_5_0_reg_1067 <= acc_5_V_fu_2076_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_5_0_reg_1067 <= 18'd261941;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_6_0_reg_1054 <= acc_6_V_fu_2082_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_6_0_reg_1054 <= 18'd262043;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_7_0_reg_1041 <= acc_7_V_fu_2088_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_7_0_reg_1041 <= 18'd262082;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_8_0_reg_1028 <= acc_8_V_fu_2094_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_8_0_reg_1028 <= 18'd262126;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2777 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_9_0_reg_1015 <= acc_9_V_fu_2100_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_9_0_reg_1015 <= 18'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln315_fu_1199_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1199_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i1_0_i_reg_718 <= i1_fu_1205_p2;
    end else if (((icmp_ln313_fu_1187_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i1_0_i_reg_718 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        i_0_i_reg_707 <= i_reg_2728;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_i_reg_707 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
        i_ic_0_i_reg_1156 <= i_ic_reg_2959;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        i_ic_0_i_reg_1156 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_fu_1294_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_index_reg_1145 <= ir_fu_1300_p2;
    end else if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        in_index_reg_1145 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        if ((1'b1 == ap_condition_620)) begin
            pX <= 32'd0;
        end else if ((1'b1 == ap_condition_618)) begin
            pX <= add_ln359_fu_2260_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        if ((1'b1 == ap_condition_556)) begin
            pY <= 32'd0;
        end else if ((1'b1 == ap_condition_405)) begin
            pY <= add_ln354_fu_2306_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        if ((1'b1 == ap_condition_620)) begin
            sX <= 32'd0;
        end else if ((1'b1 == ap_condition_618)) begin
            sX <= select_ln361_fu_2276_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        if ((1'b1 == ap_condition_556)) begin
            storemerge_i_reg_1167 <= 32'd0;
        end else if ((1'b1 == ap_condition_405)) begin
            storemerge_i_reg_1167 <= select_ln356_fu_2322_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        and_ln326_2_reg_2773 <= and_ln326_2_fu_1288_p2;
        icmp_ln326_1_reg_2756 <= icmp_ln326_1_fu_1230_p2;
        icmp_ln326_reg_2746 <= icmp_ln326_fu_1220_p2;
        pX_load_reg_2767 <= pX;
        pY_load_reg_2761 <= pY;
        sX_load_reg_2741 <= sX;
        sY_load_reg_2751 <= sY;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln326_2_reg_2773) & (1'b1 == ap_CS_fsm_state23))) begin
        i_ic_reg_2959 <= i_ic_fu_2244_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_2728 <= i_fu_1193_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln324_reg_2777 <= icmp_ln324_fu_1294_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state23) & ((1'd0 == and_ln326_2_reg_2773) | (icmp_ln338_fu_2238_p2 == 1'd1)))) begin
        icmp_ln346_reg_2969 <= icmp_ln346_fu_2255_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln346_reg_2969 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
        sY <= storemerge_i_reg_1167;
    end
end

always @ (*) begin
    if ((icmp_ln324_fu_1294_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state5 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln313_fu_1187_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln315_fu_1199_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_V_blk_n = data_V_V_empty_n;
    end else begin
        data_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((icmp_ln315_fu_1199_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1199_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_V_read = 1'b1;
    end else begin
        data_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln313_fu_1187_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer_in_V_5_address0 = zext_ln332_fu_1306_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        layer_in_V_5_address0 = grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_output_V_address0;
    end else begin
        layer_in_V_5_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer_in_V_5_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        layer_in_V_5_ce0 = grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_output_V_ce0;
    end else begin
        layer_in_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        layer_in_V_5_we0 = grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_output_V_we0;
    end else begin
        layer_in_V_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        layer_out_i_address0 = zext_ln340_fu_2250_p1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_address0 = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_address0 = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_address0 = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_address0 = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_address0 = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_address0 = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_address0 = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_address0 = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_address0 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_address0 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_address0 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        layer_out_i_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        layer_out_i_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        layer_out_i_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        layer_out_i_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        layer_out_i_address0 = 64'd0;
    end else begin
        layer_out_i_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_address1 = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_address1 = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_address1 = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_address1 = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_address1 = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_address1 = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_address1 = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_address1 = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_address1 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_address1 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_address1 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        layer_out_i_address1 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        layer_out_i_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        layer_out_i_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        layer_out_i_address1 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        layer_out_i_address1 = 64'd1;
    end else begin
        layer_out_i_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state23))) begin
        layer_out_i_ce0 = 1'b1;
    end else begin
        layer_out_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state22))) begin
        layer_out_i_ce1 = 1'b1;
    end else begin
        layer_out_i_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_d0 = acc_V_30_0_reg_742;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_d0 = acc_V_28_0_reg_768;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_d0 = acc_V_26_0_reg_794;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_d0 = acc_V_24_0_reg_820;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_d0 = acc_V_22_0_reg_846;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_d0 = acc_V_20_0_reg_872;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_d0 = acc_V_18_0_reg_898;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_d0 = acc_V_16_0_reg_924;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_d0 = acc_V_14_0_reg_950;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_d0 = acc_V_12_0_reg_976;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_d0 = acc_V_10_0_reg_1002;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        layer_out_i_d0 = acc_V_8_0_reg_1028;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        layer_out_i_d0 = acc_V_6_0_reg_1054;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        layer_out_i_d0 = acc_V_4_0_reg_1080;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        layer_out_i_d0 = acc_V_2_0_reg_1106;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        layer_out_i_d0 = acc_V_0_0_reg_1132;
    end else begin
        layer_out_i_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_d1 = acc_V_31_0_reg_729;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_d1 = acc_V_29_0_reg_755;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_d1 = acc_V_27_0_reg_781;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_d1 = acc_V_25_0_reg_807;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_d1 = acc_V_23_0_reg_833;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_d1 = acc_V_21_0_reg_859;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_d1 = acc_V_19_0_reg_885;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_d1 = acc_V_17_0_reg_911;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_d1 = acc_V_15_0_reg_937;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_d1 = acc_V_13_0_reg_963;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_d1 = acc_V_11_0_reg_989;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        layer_out_i_d1 = acc_V_9_0_reg_1015;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        layer_out_i_d1 = acc_V_7_0_reg_1041;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        layer_out_i_d1 = acc_V_5_0_reg_1067;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        layer_out_i_d1 = acc_V_3_0_reg_1093;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        layer_out_i_d1 = acc_V_1_0_reg_1119;
    end else begin
        layer_out_i_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state22))) begin
        layer_out_i_we0 = 1'b1;
    end else begin
        layer_out_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state22))) begin
        layer_out_i_we1 = 1'b1;
    end else begin
        layer_out_i_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        res_V_V_blk_n = res_V_V_full_n;
    end else begin
        res_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
        res_V_V_write = 1'b1;
    end else begin
        res_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln315_fu_1199_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmpdata_V_address0 = zext_ln317_fu_1211_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        tmpdata_V_address0 = grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_data_V_address0;
    end else begin
        tmpdata_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln315_fu_1199_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1199_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmpdata_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        tmpdata_V_ce0 = grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_data_V_ce0;
    end else begin
        tmpdata_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln315_fu_1199_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1199_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmpdata_V_we0 = 1'b1;
    end else begin
        tmpdata_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w7_V_ce0 = 1'b1;
    end else begin
        w7_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln313_fu_1187_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((icmp_ln315_fu_1199_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1199_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~((icmp_ln315_fu_1199_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1199_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'd1 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'd0 == and_ln326_2_fu_1288_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln324_fu_1294_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln324_fu_1294_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((1'b1 == ap_CS_fsm_state23) & ((1'd0 == and_ln326_2_reg_2773) | (icmp_ln338_fu_2238_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state24 : begin
            if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_0_V_fu_2046_p2 = (acc_V_0_0_reg_1132 + trunc_ln_fu_1324_p4);

assign acc_10_V_fu_2106_p2 = (acc_V_10_0_reg_1002 + trunc_ln708_4_fu_1554_p4);

assign acc_11_V_fu_2112_p2 = (acc_V_11_0_reg_989 + trunc_ln708_10_fu_1577_p4);

assign acc_12_V_fu_2118_p2 = (acc_V_12_0_reg_976 + trunc_ln708_11_fu_1600_p4);

assign acc_13_V_fu_2124_p2 = (acc_V_13_0_reg_963 + trunc_ln708_12_fu_1623_p4);

assign acc_14_V_fu_2130_p2 = (acc_V_14_0_reg_950 + trunc_ln708_13_fu_1646_p4);

assign acc_15_V_fu_2136_p2 = (acc_V_15_0_reg_937 + trunc_ln708_14_fu_1669_p4);

assign acc_16_V_fu_2142_p2 = (acc_V_16_0_reg_924 + trunc_ln708_15_fu_1692_p4);

assign acc_17_V_fu_2148_p2 = (acc_V_17_0_reg_911 + trunc_ln708_16_fu_1715_p4);

assign acc_18_V_fu_2154_p2 = (acc_V_18_0_reg_898 + trunc_ln708_17_fu_1738_p4);

assign acc_19_V_fu_2160_p2 = (acc_V_19_0_reg_885 + trunc_ln708_18_fu_1761_p4);

assign acc_1_V_fu_2052_p2 = (acc_V_1_0_reg_1119 + trunc_ln708_5_fu_1347_p4);

assign acc_20_V_fu_2166_p2 = (acc_V_20_0_reg_872 + trunc_ln708_19_fu_1784_p4);

assign acc_21_V_fu_2172_p2 = (acc_V_21_0_reg_859 + trunc_ln708_20_fu_1807_p4);

assign acc_22_V_fu_2178_p2 = (acc_V_22_0_reg_846 + trunc_ln708_21_fu_1830_p4);

assign acc_23_V_fu_2184_p2 = (acc_V_23_0_reg_833 + trunc_ln708_22_fu_1853_p4);

assign acc_24_V_fu_2190_p2 = (acc_V_24_0_reg_820 + trunc_ln708_23_fu_1876_p4);

assign acc_25_V_fu_2196_p2 = (acc_V_25_0_reg_807 + trunc_ln708_24_fu_1899_p4);

assign acc_26_V_fu_2202_p2 = (acc_V_26_0_reg_794 + trunc_ln708_25_fu_1922_p4);

assign acc_27_V_fu_2208_p2 = (acc_V_27_0_reg_781 + trunc_ln708_26_fu_1945_p4);

assign acc_28_V_fu_2214_p2 = (acc_V_28_0_reg_768 + trunc_ln708_27_fu_1968_p4);

assign acc_29_V_fu_2220_p2 = (acc_V_29_0_reg_755 + trunc_ln708_28_fu_1991_p4);

assign acc_2_V_fu_2058_p2 = (acc_V_2_0_reg_1106 + trunc_ln708_6_fu_1370_p4);

assign acc_30_V_fu_2226_p2 = (acc_V_30_0_reg_742 + trunc_ln708_29_fu_2014_p4);

assign acc_31_V_fu_2232_p2 = (acc_V_31_0_reg_729 + trunc_ln708_30_fu_2037_p4);

assign acc_3_V_fu_2064_p2 = (acc_V_3_0_reg_1093 + trunc_ln708_7_fu_1393_p4);

assign acc_4_V_fu_2070_p2 = (acc_V_4_0_reg_1080 + trunc_ln708_8_fu_1416_p4);

assign acc_5_V_fu_2076_p2 = (acc_V_5_0_reg_1067 + trunc_ln708_9_fu_1439_p4);

assign acc_6_V_fu_2082_p2 = (acc_V_6_0_reg_1054 + trunc_ln708_s_fu_1462_p4);

assign acc_7_V_fu_2088_p2 = (acc_V_7_0_reg_1041 + trunc_ln708_1_fu_1485_p4);

assign acc_8_V_fu_2094_p2 = (acc_V_8_0_reg_1028 + trunc_ln708_2_fu_1508_p4);

assign acc_9_V_fu_2100_p2 = (acc_V_9_0_reg_1015 + trunc_ln708_3_fu_1531_p4);

assign add_ln354_fu_2306_p2 = (pY_load_reg_2761 + 32'd1);

assign add_ln356_fu_2317_p2 = (sY_load_reg_2751 + 32'd1);

assign add_ln359_fu_2260_p2 = (pX_load_reg_2767 + 32'd1);

assign add_ln361_fu_2271_p2 = (sX_load_reg_2741 + 32'd1);

assign and_ln326_1_fu_1282_p2 = (icmp_ln326_3_fu_1270_p2 & icmp_ln326_2_fu_1250_p2);

assign and_ln326_2_fu_1288_p2 = (and_ln326_fu_1276_p2 & and_ln326_1_fu_1282_p2);

assign and_ln326_fu_1276_p2 = (icmp_ln326_fu_1220_p2 & icmp_ln326_1_fu_1230_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state3 = ((icmp_ln315_fu_1199_p2 == 1'd0) & (data_V_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_ignore_call0 = ((icmp_ln315_fu_1199_p2 == 1'd0) & (data_V_V_empty_n == 1'b0));
end

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_405 = (((icmp_ln350_fu_2301_p2 == 1'd0) & (1'd0 == and_ln326_2_reg_2773) & (icmp_ln346_fu_2255_p2 == 1'd1)) | ((icmp_ln350_fu_2301_p2 == 1'd0) & (icmp_ln346_fu_2255_p2 == 1'd1) & (icmp_ln338_fu_2238_p2 == 1'd1)));
end

always @ (*) begin
    ap_condition_556 = (((1'd0 == and_ln326_2_reg_2773) & (icmp_ln350_fu_2301_p2 == 1'd1) & (icmp_ln346_fu_2255_p2 == 1'd1)) | ((icmp_ln350_fu_2301_p2 == 1'd1) & (icmp_ln346_fu_2255_p2 == 1'd1) & (icmp_ln338_fu_2238_p2 == 1'd1)));
end

always @ (*) begin
    ap_condition_618 = (((icmp_ln346_fu_2255_p2 == 1'd0) & (1'd0 == and_ln326_2_reg_2773)) | ((icmp_ln346_fu_2255_p2 == 1'd0) & (icmp_ln338_fu_2238_p2 == 1'd1)));
end

always @ (*) begin
    ap_condition_620 = (((1'd0 == and_ln326_2_reg_2773) & (icmp_ln346_fu_2255_p2 == 1'd1)) | ((icmp_ln346_fu_2255_p2 == 1'd1) & (icmp_ln338_fu_2238_p2 == 1'd1)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_start = grp_cnnshift_arr_ap_fixed_ap_fixed_18_8_5_3_0_config7_s_fu_1178_ap_start_reg;

assign i1_fu_1205_p2 = (i1_0_i_reg_718 + 6'd1);

assign i_fu_1193_p2 = (i_0_i_reg_707 + 11'd1);

assign i_ic_fu_2244_p2 = (i_ic_0_i_reg_1156 + 6'd1);

assign icmp_ln313_fu_1187_p2 = ((i_0_i_reg_707 == 11'd1156) ? 1'b1 : 1'b0);

assign icmp_ln315_fu_1199_p2 = ((i1_0_i_reg_718 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln324_fu_1294_p2 = ((in_index_reg_1145 == 9'd288) ? 1'b1 : 1'b0);

assign icmp_ln326_1_fu_1230_p2 = ((sY == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln326_2_fu_1250_p2 = (($signed(tmp_3_fu_1240_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln326_3_fu_1270_p2 = (($signed(tmp_4_fu_1260_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln326_fu_1220_p2 = ((sX == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln338_fu_2238_p2 = ((i_ic_0_i_reg_1156 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln346_fu_2255_p2 = ((pX_load_reg_2767 == 32'd33) ? 1'b1 : 1'b0);

assign icmp_ln350_fu_2301_p2 = ((pY_load_reg_2761 == 32'd33) ? 1'b1 : 1'b0);

assign ir_fu_1300_p2 = (in_index_reg_1145 + 9'd1);

assign mul_ln1118_10_fu_2383_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_11_fu_2390_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_12_fu_2397_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_13_fu_2404_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_14_fu_2411_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_15_fu_2418_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_16_fu_2425_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_17_fu_2432_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_18_fu_2439_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_19_fu_2446_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_20_fu_2453_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_21_fu_2460_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_22_fu_2467_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_23_fu_2474_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_24_fu_2481_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_25_fu_2488_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_26_fu_2495_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_27_fu_2502_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_28_fu_2509_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_29_fu_2516_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_30_fu_2523_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_31_fu_2530_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_32_fu_2537_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_33_fu_2544_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_34_fu_2551_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_35_fu_2558_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_5_fu_2348_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_6_fu_2355_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_7_fu_2362_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_8_fu_2369_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_9_fu_2376_p1 = sext_ln1116_cast_fu_1316_p1;

assign mul_ln1118_fu_2341_p1 = sext_ln1116_cast_fu_1316_p1;

assign res_V_V_din = layer_out_i_q0;

assign select_ln356_fu_2322_p3 = ((icmp_ln326_1_reg_2756[0:0] === 1'b1) ? 32'd2 : add_ln356_fu_2317_p2);

assign select_ln361_fu_2276_p3 = ((icmp_ln326_reg_2746[0:0] === 1'b1) ? 32'd2 : add_ln361_fu_2271_p2);

assign sext_ln1116_cast_fu_1316_p1 = $signed(layer_in_V_5_q0);

assign start_out = real_start;

assign tmp_2_fu_2023_p4 = {{w7_V_q0[446:434]}};

assign tmp_3_fu_1240_p4 = {{pY[31:1]}};

assign tmp_48_fu_1333_p4 = {{w7_V_q0[27:14]}};

assign tmp_49_fu_1356_p4 = {{w7_V_q0[41:28]}};

assign tmp_4_fu_1260_p4 = {{pX[31:1]}};

assign tmp_50_fu_1379_p4 = {{w7_V_q0[55:42]}};

assign tmp_51_fu_1402_p4 = {{w7_V_q0[69:56]}};

assign tmp_52_fu_1425_p4 = {{w7_V_q0[83:70]}};

assign tmp_53_fu_1448_p4 = {{w7_V_q0[97:84]}};

assign tmp_54_fu_1471_p4 = {{w7_V_q0[111:98]}};

assign tmp_55_fu_1494_p4 = {{w7_V_q0[125:112]}};

assign tmp_56_fu_1517_p4 = {{w7_V_q0[139:126]}};

assign tmp_57_fu_1540_p4 = {{w7_V_q0[153:140]}};

assign tmp_58_fu_1563_p4 = {{w7_V_q0[167:154]}};

assign tmp_59_fu_1586_p4 = {{w7_V_q0[181:168]}};

assign tmp_60_fu_1609_p4 = {{w7_V_q0[195:182]}};

assign tmp_61_fu_1632_p4 = {{w7_V_q0[209:196]}};

assign tmp_62_fu_1655_p4 = {{w7_V_q0[223:210]}};

assign tmp_63_fu_1678_p4 = {{w7_V_q0[237:224]}};

assign tmp_64_fu_1701_p4 = {{w7_V_q0[251:238]}};

assign tmp_65_fu_1724_p4 = {{w7_V_q0[265:252]}};

assign tmp_66_fu_1747_p4 = {{w7_V_q0[279:266]}};

assign tmp_67_fu_1770_p4 = {{w7_V_q0[293:280]}};

assign tmp_68_fu_1793_p4 = {{w7_V_q0[307:294]}};

assign tmp_69_fu_1816_p4 = {{w7_V_q0[321:308]}};

assign tmp_70_fu_1839_p4 = {{w7_V_q0[335:322]}};

assign tmp_71_fu_1862_p4 = {{w7_V_q0[349:336]}};

assign tmp_72_fu_1885_p4 = {{w7_V_q0[363:350]}};

assign tmp_73_fu_1908_p4 = {{w7_V_q0[377:364]}};

assign tmp_74_fu_1931_p4 = {{w7_V_q0[391:378]}};

assign tmp_75_fu_1954_p4 = {{w7_V_q0[405:392]}};

assign tmp_76_fu_1977_p4 = {{w7_V_q0[419:406]}};

assign tmp_77_fu_2000_p4 = {{w7_V_q0[433:420]}};

assign trunc_ln332_fu_1312_p1 = w7_V_q0[13:0];

assign trunc_ln708_10_fu_1577_p4 = {{mul_ln1118_15_fu_2418_p2[28:11]}};

assign trunc_ln708_11_fu_1600_p4 = {{mul_ln1118_16_fu_2425_p2[28:11]}};

assign trunc_ln708_12_fu_1623_p4 = {{mul_ln1118_17_fu_2432_p2[28:11]}};

assign trunc_ln708_13_fu_1646_p4 = {{mul_ln1118_18_fu_2439_p2[28:11]}};

assign trunc_ln708_14_fu_1669_p4 = {{mul_ln1118_19_fu_2446_p2[28:11]}};

assign trunc_ln708_15_fu_1692_p4 = {{mul_ln1118_20_fu_2453_p2[28:11]}};

assign trunc_ln708_16_fu_1715_p4 = {{mul_ln1118_21_fu_2460_p2[28:11]}};

assign trunc_ln708_17_fu_1738_p4 = {{mul_ln1118_22_fu_2467_p2[28:11]}};

assign trunc_ln708_18_fu_1761_p4 = {{mul_ln1118_23_fu_2474_p2[28:11]}};

assign trunc_ln708_19_fu_1784_p4 = {{mul_ln1118_24_fu_2481_p2[28:11]}};

assign trunc_ln708_1_fu_1485_p4 = {{mul_ln1118_11_fu_2390_p2[28:11]}};

assign trunc_ln708_20_fu_1807_p4 = {{mul_ln1118_25_fu_2488_p2[28:11]}};

assign trunc_ln708_21_fu_1830_p4 = {{mul_ln1118_26_fu_2495_p2[28:11]}};

assign trunc_ln708_22_fu_1853_p4 = {{mul_ln1118_27_fu_2502_p2[28:11]}};

assign trunc_ln708_23_fu_1876_p4 = {{mul_ln1118_28_fu_2509_p2[28:11]}};

assign trunc_ln708_24_fu_1899_p4 = {{mul_ln1118_29_fu_2516_p2[28:11]}};

assign trunc_ln708_25_fu_1922_p4 = {{mul_ln1118_30_fu_2523_p2[28:11]}};

assign trunc_ln708_26_fu_1945_p4 = {{mul_ln1118_31_fu_2530_p2[28:11]}};

assign trunc_ln708_27_fu_1968_p4 = {{mul_ln1118_32_fu_2537_p2[28:11]}};

assign trunc_ln708_28_fu_1991_p4 = {{mul_ln1118_33_fu_2544_p2[28:11]}};

assign trunc_ln708_29_fu_2014_p4 = {{mul_ln1118_34_fu_2551_p2[28:11]}};

assign trunc_ln708_2_fu_1508_p4 = {{mul_ln1118_12_fu_2397_p2[28:11]}};

assign trunc_ln708_30_fu_2037_p4 = {{mul_ln1118_35_fu_2558_p2[28:11]}};

assign trunc_ln708_3_fu_1531_p4 = {{mul_ln1118_13_fu_2404_p2[28:11]}};

assign trunc_ln708_4_fu_1554_p4 = {{mul_ln1118_14_fu_2411_p2[28:11]}};

assign trunc_ln708_5_fu_1347_p4 = {{mul_ln1118_5_fu_2348_p2[28:11]}};

assign trunc_ln708_6_fu_1370_p4 = {{mul_ln1118_6_fu_2355_p2[28:11]}};

assign trunc_ln708_7_fu_1393_p4 = {{mul_ln1118_7_fu_2362_p2[28:11]}};

assign trunc_ln708_8_fu_1416_p4 = {{mul_ln1118_8_fu_2369_p2[28:11]}};

assign trunc_ln708_9_fu_1439_p4 = {{mul_ln1118_9_fu_2376_p2[28:11]}};

assign trunc_ln708_s_fu_1462_p4 = {{mul_ln1118_10_fu_2383_p2[28:11]}};

assign trunc_ln_fu_1324_p4 = {{mul_ln1118_fu_2341_p2[28:11]}};

assign w7_V_address0 = zext_ln332_fu_1306_p1;

assign zext_ln317_fu_1211_p1 = i1_0_i_reg_718;

assign zext_ln332_fu_1306_p1 = in_index_reg_1145;

assign zext_ln340_fu_2250_p1 = i_ic_0_i_reg_1156;

endmodule //conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_s
