// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcu250-figd2104-2L-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.273000,HLS_SYN_LAT=6200185,HLS_SYN_TPT=6167262,HLS_SYN_MEM=179,HLS_SYN_DSP=293,HLS_SYN_FF=11117,HLS_SYN_LUT=28600,HLS_VERSION=2019_2}" *)

module myproject (
        input_1_V_V_TDATA,
        layer34_out_V_V_TDATA,
        ap_clk,
        ap_rst_n,
        input_1_V_V_TVALID,
        input_1_V_V_TREADY,
        ap_start,
        layer34_out_V_V_TVALID,
        layer34_out_V_V_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [15:0] input_1_V_V_TDATA;
output  [15:0] layer34_out_V_V_TDATA;
input   ap_clk;
input   ap_rst_n;
input   input_1_V_V_TVALID;
output   input_1_V_V_TREADY;
input   ap_start;
output   layer34_out_V_V_TVALID;
input   layer34_out_V_V_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_ap_start;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_ap_done;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_ap_continue;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_ap_idle;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_ap_ready;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_start_out;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_start_write;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_data_V_V_TREADY;
wire   [17:0] zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_res_V_V_din;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_res_V_V_write;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_ap_start;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_ap_done;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_ap_continue;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_ap_idle;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_ap_ready;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_start_out;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_start_write;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_data_V_V_read;
wire   [17:0] conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_res_V_V_din;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_res_V_V_write;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_ap_start;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_ap_done;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_ap_continue;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_ap_idle;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_ap_ready;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_start_out;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_start_write;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_data_V_V_read;
wire   [17:0] relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_res_V_V_din;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_res_V_V_write;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_ap_start;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_ap_done;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_ap_continue;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_ap_idle;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_ap_ready;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_start_out;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_start_write;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_data_V_V_read;
wire   [17:0] zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_res_V_V_din;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_res_V_V_write;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_ap_start;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_ap_done;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_ap_continue;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_ap_idle;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_ap_ready;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_start_out;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_start_write;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_data_V_V_read;
wire   [17:0] conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_res_V_V_din;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_res_V_V_write;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_ap_start;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_ap_done;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_ap_continue;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_ap_idle;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_ap_ready;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_start_out;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_start_write;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_data_V_V_read;
wire   [17:0] relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_res_V_V_din;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_res_V_V_write;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_ap_start;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_ap_done;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_ap_continue;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_ap_idle;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_ap_ready;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_start_out;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_start_write;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_data_V_V_read;
wire   [17:0] pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_res_V_V_din;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_res_V_V_write;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_ap_start;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_ap_done;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_ap_continue;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_ap_idle;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_ap_ready;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_start_out;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_start_write;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_data_V_V_read;
wire   [17:0] zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_res_V_V_din;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_res_V_V_write;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_ap_start;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_ap_done;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_ap_continue;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_ap_idle;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_ap_ready;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_start_out;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_start_write;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_data_V_V_read;
wire   [17:0] conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_res_V_V_din;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_res_V_V_write;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_ap_start;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_ap_done;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_ap_continue;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_ap_idle;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_ap_ready;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_start_out;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_start_write;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_data_V_V_read;
wire   [17:0] relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_res_V_V_din;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_res_V_V_write;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_ap_start;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_ap_done;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_ap_continue;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_ap_idle;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_ap_ready;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_start_out;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_start_write;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_data_V_V_read;
wire   [17:0] zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_res_V_V_din;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_res_V_V_write;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_ap_start;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_ap_done;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_ap_continue;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_ap_idle;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_ap_ready;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_start_out;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_start_write;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_data_V_V_read;
wire   [17:0] conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_res_V_V_din;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_res_V_V_write;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_ap_start;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_ap_done;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_ap_continue;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_ap_idle;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_ap_ready;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_start_out;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_start_write;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_data_V_V_read;
wire   [17:0] relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_res_V_V_din;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_res_V_V_write;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_ap_start;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_ap_done;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_ap_continue;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_ap_idle;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_ap_ready;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_start_out;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_start_write;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_data_V_V_read;
wire   [17:0] pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_res_V_V_din;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_res_V_V_write;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_ap_start;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_ap_done;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_ap_continue;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_ap_idle;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_ap_ready;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_start_out;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_start_write;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_data_V_V_read;
wire   [17:0] zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_res_V_V_din;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_res_V_V_write;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_ap_start;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_ap_done;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_ap_continue;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_ap_idle;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_ap_ready;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_start_out;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_start_write;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_data_V_V_read;
wire   [17:0] conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_res_V_V_din;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_res_V_V_write;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_ap_start;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_ap_done;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_ap_continue;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_ap_idle;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_ap_ready;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_start_out;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_start_write;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_data_V_V_read;
wire   [17:0] relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_res_V_V_din;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_res_V_V_write;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_ap_start;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_ap_done;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_ap_continue;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_ap_idle;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_ap_ready;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_start_out;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_start_write;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_data_V_V_read;
wire   [17:0] zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_res_V_V_din;
wire    zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_res_V_V_write;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_ap_start;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_ap_done;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_ap_continue;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_ap_idle;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_ap_ready;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_start_out;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_start_write;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_data_V_V_read;
wire   [17:0] conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_res_V_V_din;
wire    conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_res_V_V_write;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_ap_start;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_ap_done;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_ap_continue;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_ap_idle;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_ap_ready;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_start_out;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_start_write;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_data_V_V_read;
wire   [17:0] relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_res_V_V_din;
wire    relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_res_V_V_write;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_ap_start;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_ap_done;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_ap_continue;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_ap_idle;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_ap_ready;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_start_out;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_start_write;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_data_V_V_read;
wire   [17:0] pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_res_V_V_din;
wire    pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_res_V_V_write;
wire    dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_ap_start;
wire    dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_ap_done;
wire    dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_ap_continue;
wire    dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_ap_idle;
wire    dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_ap_ready;
wire    dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_start_out;
wire    dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_start_write;
wire    dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_data_V_V_read;
wire   [17:0] dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_res_V_V_din;
wire    dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_res_V_V_write;
wire    sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_ap_start;
wire    sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_ap_done;
wire    sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_ap_continue;
wire    sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_ap_idle;
wire    sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_ap_ready;
wire    sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_data_V_V_read;
wire   [15:0] sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_res_V_V_TDATA;
wire    sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_res_V_V_TVALID;
wire    ap_sync_continue;
wire    layer35_out_V_V_full_n;
wire   [17:0] layer35_out_V_V_dout;
wire    layer35_out_V_V_empty_n;
wire    layer3_out_V_V_full_n;
wire   [17:0] layer3_out_V_V_dout;
wire    layer3_out_V_V_empty_n;
wire    layer6_out_V_V_full_n;
wire   [17:0] layer6_out_V_V_dout;
wire    layer6_out_V_V_empty_n;
wire    layer36_out_V_V_full_n;
wire   [17:0] layer36_out_V_V_dout;
wire    layer36_out_V_V_empty_n;
wire    layer7_out_V_V_full_n;
wire   [17:0] layer7_out_V_V_dout;
wire    layer7_out_V_V_empty_n;
wire    layer10_out_V_V_full_n;
wire   [17:0] layer10_out_V_V_dout;
wire    layer10_out_V_V_empty_n;
wire    layer11_out_V_V_full_n;
wire   [17:0] layer11_out_V_V_dout;
wire    layer11_out_V_V_empty_n;
wire    layer37_out_V_V_full_n;
wire   [17:0] layer37_out_V_V_dout;
wire    layer37_out_V_V_empty_n;
wire    layer12_out_V_V_full_n;
wire   [17:0] layer12_out_V_V_dout;
wire    layer12_out_V_V_empty_n;
wire    layer15_out_V_V_full_n;
wire   [17:0] layer15_out_V_V_dout;
wire    layer15_out_V_V_empty_n;
wire    layer38_out_V_V_full_n;
wire   [17:0] layer38_out_V_V_dout;
wire    layer38_out_V_V_empty_n;
wire    layer16_out_V_V_full_n;
wire   [17:0] layer16_out_V_V_dout;
wire    layer16_out_V_V_empty_n;
wire    layer19_out_V_V_full_n;
wire   [17:0] layer19_out_V_V_dout;
wire    layer19_out_V_V_empty_n;
wire    layer20_out_V_V_full_n;
wire   [17:0] layer20_out_V_V_dout;
wire    layer20_out_V_V_empty_n;
wire    layer39_out_V_V_full_n;
wire   [17:0] layer39_out_V_V_dout;
wire    layer39_out_V_V_empty_n;
wire    layer21_out_V_V_full_n;
wire   [17:0] layer21_out_V_V_dout;
wire    layer21_out_V_V_empty_n;
wire    layer24_out_V_V_full_n;
wire   [17:0] layer24_out_V_V_dout;
wire    layer24_out_V_V_empty_n;
wire    layer40_out_V_V_full_n;
wire   [17:0] layer40_out_V_V_dout;
wire    layer40_out_V_V_empty_n;
wire    layer25_out_V_V_full_n;
wire   [17:0] layer25_out_V_V_dout;
wire    layer25_out_V_V_empty_n;
wire    layer28_out_V_V_full_n;
wire   [17:0] layer28_out_V_V_dout;
wire    layer28_out_V_V_empty_n;
wire    layer29_out_V_V_full_n;
wire   [17:0] layer29_out_V_V_dout;
wire    layer29_out_V_V_empty_n;
wire    layer31_out_V_V_full_n;
wire   [17:0] layer31_out_V_V_dout;
wire    layer31_out_V_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_din;
wire    start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_dout;
wire    start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_empty_n;
wire   [0:0] start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_din;
wire    start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_full_n;
wire   [0:0] start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_dout;
wire    start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_empty_n;
wire   [0:0] start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_din;
wire    start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_full_n;
wire   [0:0] start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_dout;
wire    start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_din;
wire    start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_dout;
wire    start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_empty_n;
wire   [0:0] start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_din;
wire    start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_full_n;
wire   [0:0] start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_dout;
wire    start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_empty_n;
wire   [0:0] start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_din;
wire    start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_full_n;
wire   [0:0] start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_dout;
wire    start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_empty_n;
wire   [0:0] start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_din;
wire    start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_full_n;
wire   [0:0] start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_dout;
wire    start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_din;
wire    start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_dout;
wire    start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_empty_n;
wire   [0:0] start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_din;
wire    start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_full_n;
wire   [0:0] start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_dout;
wire    start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_empty_n;
wire   [0:0] start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_din;
wire    start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_full_n;
wire   [0:0] start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_dout;
wire    start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_din;
wire    start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_dout;
wire    start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_empty_n;
wire   [0:0] start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_din;
wire    start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_full_n;
wire   [0:0] start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_dout;
wire    start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_empty_n;
wire   [0:0] start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_din;
wire    start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_full_n;
wire   [0:0] start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_dout;
wire    start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_empty_n;
wire   [0:0] start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_din;
wire    start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_full_n;
wire   [0:0] start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_dout;
wire    start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_din;
wire    start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_dout;
wire    start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_empty_n;
wire   [0:0] start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_din;
wire    start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_full_n;
wire   [0:0] start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_dout;
wire    start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_empty_n;
wire   [0:0] start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_din;
wire    start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_full_n;
wire   [0:0] start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_dout;
wire    start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_din;
wire    start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_dout;
wire    start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_empty_n;
wire   [0:0] start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_din;
wire    start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_full_n;
wire   [0:0] start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_dout;
wire    start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_empty_n;
wire   [0:0] start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_din;
wire    start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_full_n;
wire   [0:0] start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_dout;
wire    start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_empty_n;
wire   [0:0] start_for_dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_din;
wire    start_for_dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_full_n;
wire   [0:0] start_for_dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_dout;
wire    start_for_dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_empty_n;
wire   [0:0] start_for_sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_din;
wire    start_for_sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_full_n;
wire   [0:0] start_for_sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_dout;
wire    start_for_sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_empty_n;
wire    sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_start_full_n;
wire    sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_start_write;

zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_s zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_full_n),
    .ap_done(zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_ap_done),
    .ap_continue(zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_ap_continue),
    .ap_idle(zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_ap_idle),
    .ap_ready(zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_ap_ready),
    .start_out(zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_start_out),
    .start_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_start_write),
    .data_V_V_TDATA(input_1_V_V_TDATA),
    .data_V_V_TVALID(input_1_V_V_TVALID),
    .data_V_V_TREADY(zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_data_V_V_TREADY),
    .res_V_V_din(zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_res_V_V_din),
    .res_V_V_full_n(layer35_out_V_V_full_n),
    .res_V_V_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_res_V_V_write)
);

conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_s conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_ap_start),
    .start_full_n(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_full_n),
    .ap_done(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_ap_done),
    .ap_continue(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_ap_continue),
    .ap_idle(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_ap_idle),
    .ap_ready(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_ap_ready),
    .start_out(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_start_out),
    .start_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_start_write),
    .data_V_V_dout(layer35_out_V_V_dout),
    .data_V_V_empty_n(layer35_out_V_V_empty_n),
    .data_V_V_read(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_data_V_V_read),
    .res_V_V_din(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_res_V_V_din),
    .res_V_V_full_n(layer3_out_V_V_full_n),
    .res_V_V_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_res_V_V_write)
);

relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_s relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_ap_start),
    .start_full_n(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_full_n),
    .ap_done(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_ap_done),
    .ap_continue(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_ap_continue),
    .ap_idle(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_ap_idle),
    .ap_ready(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_ap_ready),
    .start_out(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_start_out),
    .start_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_start_write),
    .data_V_V_dout(layer3_out_V_V_dout),
    .data_V_V_empty_n(layer3_out_V_V_empty_n),
    .data_V_V_read(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_data_V_V_read),
    .res_V_V_din(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_res_V_V_din),
    .res_V_V_full_n(layer6_out_V_V_full_n),
    .res_V_V_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_res_V_V_write)
);

zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_s zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_full_n),
    .ap_done(zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_ap_done),
    .ap_continue(zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_ap_continue),
    .ap_idle(zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_ap_idle),
    .ap_ready(zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_ap_ready),
    .start_out(zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_start_out),
    .start_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_start_write),
    .data_V_V_dout(layer6_out_V_V_dout),
    .data_V_V_empty_n(layer6_out_V_V_empty_n),
    .data_V_V_read(zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_data_V_V_read),
    .res_V_V_din(zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_res_V_V_din),
    .res_V_V_full_n(layer36_out_V_V_full_n),
    .res_V_V_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_res_V_V_write)
);

conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_s conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_ap_start),
    .start_full_n(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_full_n),
    .ap_done(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_ap_done),
    .ap_continue(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_ap_continue),
    .ap_idle(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_ap_idle),
    .ap_ready(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_ap_ready),
    .start_out(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_start_out),
    .start_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_start_write),
    .data_V_V_dout(layer36_out_V_V_dout),
    .data_V_V_empty_n(layer36_out_V_V_empty_n),
    .data_V_V_read(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_data_V_V_read),
    .res_V_V_din(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_res_V_V_din),
    .res_V_V_full_n(layer7_out_V_V_full_n),
    .res_V_V_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_res_V_V_write)
);

relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_s relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_ap_start),
    .start_full_n(start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_full_n),
    .ap_done(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_ap_done),
    .ap_continue(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_ap_continue),
    .ap_idle(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_ap_idle),
    .ap_ready(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_ap_ready),
    .start_out(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_start_out),
    .start_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_start_write),
    .data_V_V_dout(layer7_out_V_V_dout),
    .data_V_V_empty_n(layer7_out_V_V_empty_n),
    .data_V_V_read(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_data_V_V_read),
    .res_V_V_din(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_res_V_V_din),
    .res_V_V_full_n(layer10_out_V_V_full_n),
    .res_V_V_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_res_V_V_write)
);

pooling2d_cl_ss_ap_fixed_ap_fixed_config11_s pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_ap_start),
    .start_full_n(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_full_n),
    .ap_done(pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_ap_done),
    .ap_continue(pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_ap_continue),
    .ap_idle(pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_ap_idle),
    .ap_ready(pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_ap_ready),
    .start_out(pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_start_out),
    .start_write(pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_start_write),
    .data_V_V_dout(layer10_out_V_V_dout),
    .data_V_V_empty_n(layer10_out_V_V_empty_n),
    .data_V_V_read(pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_data_V_V_read),
    .res_V_V_din(pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_res_V_V_din),
    .res_V_V_full_n(layer11_out_V_V_full_n),
    .res_V_V_write(pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_res_V_V_write)
);

zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_s zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_full_n),
    .ap_done(zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_ap_done),
    .ap_continue(zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_ap_continue),
    .ap_idle(zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_ap_idle),
    .ap_ready(zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_ap_ready),
    .start_out(zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_start_out),
    .start_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_start_write),
    .data_V_V_dout(layer11_out_V_V_dout),
    .data_V_V_empty_n(layer11_out_V_V_empty_n),
    .data_V_V_read(zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_data_V_V_read),
    .res_V_V_din(zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_res_V_V_din),
    .res_V_V_full_n(layer37_out_V_V_full_n),
    .res_V_V_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_res_V_V_write)
);

conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_s conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_ap_start),
    .start_full_n(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_full_n),
    .ap_done(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_ap_done),
    .ap_continue(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_ap_continue),
    .ap_idle(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_ap_idle),
    .ap_ready(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_ap_ready),
    .start_out(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_start_out),
    .start_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_start_write),
    .data_V_V_dout(layer37_out_V_V_dout),
    .data_V_V_empty_n(layer37_out_V_V_empty_n),
    .data_V_V_read(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_data_V_V_read),
    .res_V_V_din(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_res_V_V_din),
    .res_V_V_full_n(layer12_out_V_V_full_n),
    .res_V_V_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_res_V_V_write)
);

relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_s relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_ap_start),
    .start_full_n(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_full_n),
    .ap_done(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_ap_done),
    .ap_continue(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_ap_continue),
    .ap_idle(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_ap_idle),
    .ap_ready(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_ap_ready),
    .start_out(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_start_out),
    .start_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_start_write),
    .data_V_V_dout(layer12_out_V_V_dout),
    .data_V_V_empty_n(layer12_out_V_V_empty_n),
    .data_V_V_read(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_data_V_V_read),
    .res_V_V_din(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_res_V_V_din),
    .res_V_V_full_n(layer15_out_V_V_full_n),
    .res_V_V_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_res_V_V_write)
);

zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_s zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_full_n),
    .ap_done(zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_ap_done),
    .ap_continue(zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_ap_continue),
    .ap_idle(zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_ap_idle),
    .ap_ready(zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_ap_ready),
    .start_out(zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_start_out),
    .start_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_start_write),
    .data_V_V_dout(layer15_out_V_V_dout),
    .data_V_V_empty_n(layer15_out_V_V_empty_n),
    .data_V_V_read(zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_data_V_V_read),
    .res_V_V_din(zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_res_V_V_din),
    .res_V_V_full_n(layer38_out_V_V_full_n),
    .res_V_V_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_res_V_V_write)
);

conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_s conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_ap_start),
    .start_full_n(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_full_n),
    .ap_done(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_ap_done),
    .ap_continue(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_ap_continue),
    .ap_idle(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_ap_idle),
    .ap_ready(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_ap_ready),
    .start_out(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_start_out),
    .start_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_start_write),
    .data_V_V_dout(layer38_out_V_V_dout),
    .data_V_V_empty_n(layer38_out_V_V_empty_n),
    .data_V_V_read(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_data_V_V_read),
    .res_V_V_din(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_res_V_V_din),
    .res_V_V_full_n(layer16_out_V_V_full_n),
    .res_V_V_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_res_V_V_write)
);

relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_s relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_ap_start),
    .start_full_n(start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_full_n),
    .ap_done(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_ap_done),
    .ap_continue(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_ap_continue),
    .ap_idle(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_ap_idle),
    .ap_ready(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_ap_ready),
    .start_out(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_start_out),
    .start_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_start_write),
    .data_V_V_dout(layer16_out_V_V_dout),
    .data_V_V_empty_n(layer16_out_V_V_empty_n),
    .data_V_V_read(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_data_V_V_read),
    .res_V_V_din(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_res_V_V_din),
    .res_V_V_full_n(layer19_out_V_V_full_n),
    .res_V_V_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_res_V_V_write)
);

pooling2d_cl_ss_ap_fixed_ap_fixed_config20_s pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_ap_start),
    .start_full_n(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_full_n),
    .ap_done(pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_ap_done),
    .ap_continue(pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_ap_continue),
    .ap_idle(pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_ap_idle),
    .ap_ready(pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_ap_ready),
    .start_out(pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_start_out),
    .start_write(pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_start_write),
    .data_V_V_dout(layer19_out_V_V_dout),
    .data_V_V_empty_n(layer19_out_V_V_empty_n),
    .data_V_V_read(pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_data_V_V_read),
    .res_V_V_din(pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_res_V_V_din),
    .res_V_V_full_n(layer20_out_V_V_full_n),
    .res_V_V_write(pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_res_V_V_write)
);

zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_s zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_full_n),
    .ap_done(zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_ap_done),
    .ap_continue(zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_ap_continue),
    .ap_idle(zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_ap_idle),
    .ap_ready(zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_ap_ready),
    .start_out(zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_start_out),
    .start_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_start_write),
    .data_V_V_dout(layer20_out_V_V_dout),
    .data_V_V_empty_n(layer20_out_V_V_empty_n),
    .data_V_V_read(zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_data_V_V_read),
    .res_V_V_din(zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_res_V_V_din),
    .res_V_V_full_n(layer39_out_V_V_full_n),
    .res_V_V_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_res_V_V_write)
);

conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_s conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_ap_start),
    .start_full_n(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_full_n),
    .ap_done(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_ap_done),
    .ap_continue(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_ap_continue),
    .ap_idle(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_ap_idle),
    .ap_ready(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_ap_ready),
    .start_out(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_start_out),
    .start_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_start_write),
    .data_V_V_dout(layer39_out_V_V_dout),
    .data_V_V_empty_n(layer39_out_V_V_empty_n),
    .data_V_V_read(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_data_V_V_read),
    .res_V_V_din(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_res_V_V_din),
    .res_V_V_full_n(layer21_out_V_V_full_n),
    .res_V_V_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_res_V_V_write)
);

relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_s relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_ap_start),
    .start_full_n(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_full_n),
    .ap_done(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_ap_done),
    .ap_continue(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_ap_continue),
    .ap_idle(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_ap_idle),
    .ap_ready(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_ap_ready),
    .start_out(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_start_out),
    .start_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_start_write),
    .data_V_V_dout(layer21_out_V_V_dout),
    .data_V_V_empty_n(layer21_out_V_V_empty_n),
    .data_V_V_read(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_data_V_V_read),
    .res_V_V_din(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_res_V_V_din),
    .res_V_V_full_n(layer24_out_V_V_full_n),
    .res_V_V_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_res_V_V_write)
);

zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_s zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_full_n),
    .ap_done(zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_ap_done),
    .ap_continue(zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_ap_continue),
    .ap_idle(zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_ap_idle),
    .ap_ready(zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_ap_ready),
    .start_out(zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_start_out),
    .start_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_start_write),
    .data_V_V_dout(layer24_out_V_V_dout),
    .data_V_V_empty_n(layer24_out_V_V_empty_n),
    .data_V_V_read(zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_data_V_V_read),
    .res_V_V_din(zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_res_V_V_din),
    .res_V_V_full_n(layer40_out_V_V_full_n),
    .res_V_V_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_res_V_V_write)
);

conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_s conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_ap_start),
    .start_full_n(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_full_n),
    .ap_done(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_ap_done),
    .ap_continue(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_ap_continue),
    .ap_idle(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_ap_idle),
    .ap_ready(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_ap_ready),
    .start_out(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_start_out),
    .start_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_start_write),
    .data_V_V_dout(layer40_out_V_V_dout),
    .data_V_V_empty_n(layer40_out_V_V_empty_n),
    .data_V_V_read(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_data_V_V_read),
    .res_V_V_din(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_res_V_V_din),
    .res_V_V_full_n(layer25_out_V_V_full_n),
    .res_V_V_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_res_V_V_write)
);

relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_s relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_ap_start),
    .start_full_n(start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_full_n),
    .ap_done(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_ap_done),
    .ap_continue(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_ap_continue),
    .ap_idle(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_ap_idle),
    .ap_ready(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_ap_ready),
    .start_out(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_start_out),
    .start_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_start_write),
    .data_V_V_dout(layer25_out_V_V_dout),
    .data_V_V_empty_n(layer25_out_V_V_empty_n),
    .data_V_V_read(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_data_V_V_read),
    .res_V_V_din(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_res_V_V_din),
    .res_V_V_full_n(layer28_out_V_V_full_n),
    .res_V_V_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_res_V_V_write)
);

pooling2d_cl_ss_ap_fixed_ap_fixed_config29_s pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_ap_start),
    .start_full_n(start_for_dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_full_n),
    .ap_done(pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_ap_done),
    .ap_continue(pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_ap_continue),
    .ap_idle(pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_ap_idle),
    .ap_ready(pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_ap_ready),
    .start_out(pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_start_out),
    .start_write(pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_start_write),
    .data_V_V_dout(layer28_out_V_V_dout),
    .data_V_V_empty_n(layer28_out_V_V_empty_n),
    .data_V_V_read(pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_data_V_V_read),
    .res_V_V_din(pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_res_V_V_din),
    .res_V_V_full_n(layer29_out_V_V_full_n),
    .res_V_V_write(pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_res_V_V_write)
);

dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_s dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_ap_start),
    .start_full_n(start_for_sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_full_n),
    .ap_done(dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_ap_done),
    .ap_continue(dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_ap_continue),
    .ap_idle(dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_ap_idle),
    .ap_ready(dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_ap_ready),
    .start_out(dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_start_out),
    .start_write(dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_start_write),
    .data_V_V_dout(layer29_out_V_V_dout),
    .data_V_V_empty_n(layer29_out_V_V_empty_n),
    .data_V_V_read(dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_data_V_V_read),
    .res_V_V_din(dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_res_V_V_din),
    .res_V_V_full_n(layer31_out_V_V_full_n),
    .res_V_V_write(dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_res_V_V_write)
);

sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_s sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_ap_start),
    .ap_done(sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_ap_done),
    .ap_continue(sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_ap_continue),
    .ap_idle(sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_ap_idle),
    .ap_ready(sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_ap_ready),
    .data_V_V_dout(layer31_out_V_V_dout),
    .data_V_V_empty_n(layer31_out_V_V_empty_n),
    .data_V_V_read(sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_data_V_V_read),
    .res_V_V_TDATA(sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_res_V_V_TDATA),
    .res_V_V_TVALID(sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_res_V_V_TVALID),
    .res_V_V_TREADY(layer34_out_V_V_TREADY)
);

fifo_w18_d1_A layer35_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_res_V_V_din),
    .if_full_n(layer35_out_V_V_full_n),
    .if_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_res_V_V_write),
    .if_dout(layer35_out_V_V_dout),
    .if_empty_n(layer35_out_V_V_empty_n),
    .if_read(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_data_V_V_read)
);

fifo_w18_d1_A layer3_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_res_V_V_din),
    .if_full_n(layer3_out_V_V_full_n),
    .if_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_res_V_V_write),
    .if_dout(layer3_out_V_V_dout),
    .if_empty_n(layer3_out_V_V_empty_n),
    .if_read(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_data_V_V_read)
);

fifo_w18_d1_A layer6_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_res_V_V_din),
    .if_full_n(layer6_out_V_V_full_n),
    .if_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_res_V_V_write),
    .if_dout(layer6_out_V_V_dout),
    .if_empty_n(layer6_out_V_V_empty_n),
    .if_read(zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_data_V_V_read)
);

fifo_w18_d1_A layer36_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_res_V_V_din),
    .if_full_n(layer36_out_V_V_full_n),
    .if_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_res_V_V_write),
    .if_dout(layer36_out_V_V_dout),
    .if_empty_n(layer36_out_V_V_empty_n),
    .if_read(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_data_V_V_read)
);

fifo_w18_d1_A layer7_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_res_V_V_din),
    .if_full_n(layer7_out_V_V_full_n),
    .if_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_res_V_V_write),
    .if_dout(layer7_out_V_V_dout),
    .if_empty_n(layer7_out_V_V_empty_n),
    .if_read(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_data_V_V_read)
);

fifo_w18_d1_A layer10_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_res_V_V_din),
    .if_full_n(layer10_out_V_V_full_n),
    .if_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_res_V_V_write),
    .if_dout(layer10_out_V_V_dout),
    .if_empty_n(layer10_out_V_V_empty_n),
    .if_read(pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_data_V_V_read)
);

fifo_w18_d1_A layer11_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_res_V_V_din),
    .if_full_n(layer11_out_V_V_full_n),
    .if_write(pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_res_V_V_write),
    .if_dout(layer11_out_V_V_dout),
    .if_empty_n(layer11_out_V_V_empty_n),
    .if_read(zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_data_V_V_read)
);

fifo_w18_d1_A layer37_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_res_V_V_din),
    .if_full_n(layer37_out_V_V_full_n),
    .if_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_res_V_V_write),
    .if_dout(layer37_out_V_V_dout),
    .if_empty_n(layer37_out_V_V_empty_n),
    .if_read(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_data_V_V_read)
);

fifo_w18_d1_A layer12_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_res_V_V_din),
    .if_full_n(layer12_out_V_V_full_n),
    .if_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_res_V_V_write),
    .if_dout(layer12_out_V_V_dout),
    .if_empty_n(layer12_out_V_V_empty_n),
    .if_read(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_data_V_V_read)
);

fifo_w18_d1_A layer15_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_res_V_V_din),
    .if_full_n(layer15_out_V_V_full_n),
    .if_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_res_V_V_write),
    .if_dout(layer15_out_V_V_dout),
    .if_empty_n(layer15_out_V_V_empty_n),
    .if_read(zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_data_V_V_read)
);

fifo_w18_d1_A layer38_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_res_V_V_din),
    .if_full_n(layer38_out_V_V_full_n),
    .if_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_res_V_V_write),
    .if_dout(layer38_out_V_V_dout),
    .if_empty_n(layer38_out_V_V_empty_n),
    .if_read(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_data_V_V_read)
);

fifo_w18_d1_A layer16_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_res_V_V_din),
    .if_full_n(layer16_out_V_V_full_n),
    .if_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_res_V_V_write),
    .if_dout(layer16_out_V_V_dout),
    .if_empty_n(layer16_out_V_V_empty_n),
    .if_read(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_data_V_V_read)
);

fifo_w18_d1_A layer19_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_res_V_V_din),
    .if_full_n(layer19_out_V_V_full_n),
    .if_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_res_V_V_write),
    .if_dout(layer19_out_V_V_dout),
    .if_empty_n(layer19_out_V_V_empty_n),
    .if_read(pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_data_V_V_read)
);

fifo_w18_d1_A layer20_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_res_V_V_din),
    .if_full_n(layer20_out_V_V_full_n),
    .if_write(pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_res_V_V_write),
    .if_dout(layer20_out_V_V_dout),
    .if_empty_n(layer20_out_V_V_empty_n),
    .if_read(zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_data_V_V_read)
);

fifo_w18_d1_A layer39_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_res_V_V_din),
    .if_full_n(layer39_out_V_V_full_n),
    .if_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_res_V_V_write),
    .if_dout(layer39_out_V_V_dout),
    .if_empty_n(layer39_out_V_V_empty_n),
    .if_read(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_data_V_V_read)
);

fifo_w18_d1_A layer21_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_res_V_V_din),
    .if_full_n(layer21_out_V_V_full_n),
    .if_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_res_V_V_write),
    .if_dout(layer21_out_V_V_dout),
    .if_empty_n(layer21_out_V_V_empty_n),
    .if_read(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_data_V_V_read)
);

fifo_w18_d1_A layer24_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_res_V_V_din),
    .if_full_n(layer24_out_V_V_full_n),
    .if_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_res_V_V_write),
    .if_dout(layer24_out_V_V_dout),
    .if_empty_n(layer24_out_V_V_empty_n),
    .if_read(zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_data_V_V_read)
);

fifo_w18_d1_A layer40_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_res_V_V_din),
    .if_full_n(layer40_out_V_V_full_n),
    .if_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_res_V_V_write),
    .if_dout(layer40_out_V_V_dout),
    .if_empty_n(layer40_out_V_V_empty_n),
    .if_read(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_data_V_V_read)
);

fifo_w18_d1_A layer25_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_res_V_V_din),
    .if_full_n(layer25_out_V_V_full_n),
    .if_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_res_V_V_write),
    .if_dout(layer25_out_V_V_dout),
    .if_empty_n(layer25_out_V_V_empty_n),
    .if_read(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_data_V_V_read)
);

fifo_w18_d1_A layer28_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_res_V_V_din),
    .if_full_n(layer28_out_V_V_full_n),
    .if_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_res_V_V_write),
    .if_dout(layer28_out_V_V_dout),
    .if_empty_n(layer28_out_V_V_empty_n),
    .if_read(pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_data_V_V_read)
);

fifo_w18_d1_A layer29_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_res_V_V_din),
    .if_full_n(layer29_out_V_V_full_n),
    .if_write(pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_res_V_V_write),
    .if_dout(layer29_out_V_V_dout),
    .if_empty_n(layer29_out_V_V_empty_n),
    .if_read(dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_data_V_V_read)
);

fifo_w18_d1_A layer31_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_res_V_V_din),
    .if_full_n(layer31_out_V_V_full_n),
    .if_write(dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_res_V_V_write),
    .if_dout(layer31_out_V_V_dout),
    .if_empty_n(layer31_out_V_V_empty_n),
    .if_read(sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_data_V_V_read)
);

start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_confGfk start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_confGfk_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_din),
    .if_full_n(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_full_n),
    .if_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_start_write),
    .if_dout(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_empty_n),
    .if_read(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_ap_ready)
);

start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_confiHfu start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_confiHfu_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_din),
    .if_full_n(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_full_n),
    .if_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_start_write),
    .if_dout(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_dout),
    .if_empty_n(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_empty_n),
    .if_read(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_ap_ready)
);

start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0 start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_din),
    .if_full_n(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_full_n),
    .if_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_start_write),
    .if_dout(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_dout),
    .if_empty_n(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_empty_n),
    .if_read(zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_ap_ready)
);

start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_confIfE start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_confIfE_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_din),
    .if_full_n(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_full_n),
    .if_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_start_write),
    .if_dout(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_empty_n),
    .if_read(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_ap_ready)
);

start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_confiJfO start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_confiJfO_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_din),
    .if_full_n(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_full_n),
    .if_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_start_write),
    .if_dout(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_dout),
    .if_empty_n(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_empty_n),
    .if_read(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_ap_ready)
);

start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0 start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_din),
    .if_full_n(start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_full_n),
    .if_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_start_write),
    .if_dout(start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_dout),
    .if_empty_n(start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_empty_n),
    .if_read(pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_ap_ready)
);

start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0 start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_din),
    .if_full_n(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_full_n),
    .if_write(pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_start_write),
    .if_dout(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_dout),
    .if_empty_n(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_empty_n),
    .if_read(zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_ap_ready)
);

start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_confKfY start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_confKfY_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_din),
    .if_full_n(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_full_n),
    .if_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_start_write),
    .if_dout(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_empty_n),
    .if_read(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_ap_ready)
);

start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_confiLf8 start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_confiLf8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_din),
    .if_full_n(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_full_n),
    .if_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_start_write),
    .if_dout(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_dout),
    .if_empty_n(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_empty_n),
    .if_read(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_ap_ready)
);

start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0 start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_din),
    .if_full_n(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_full_n),
    .if_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_start_write),
    .if_dout(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_dout),
    .if_empty_n(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_empty_n),
    .if_read(zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_ap_ready)
);

start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_confMgi start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_confMgi_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_din),
    .if_full_n(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_full_n),
    .if_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_start_write),
    .if_dout(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_empty_n),
    .if_read(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_ap_ready)
);

start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_confiNgs start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_confiNgs_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_din),
    .if_full_n(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_full_n),
    .if_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_start_write),
    .if_dout(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_dout),
    .if_empty_n(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_empty_n),
    .if_read(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_ap_ready)
);

start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0 start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_din),
    .if_full_n(start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_full_n),
    .if_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_start_write),
    .if_dout(start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_dout),
    .if_empty_n(start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_empty_n),
    .if_read(pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_ap_ready)
);

start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0 start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_din),
    .if_full_n(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_full_n),
    .if_write(pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_start_write),
    .if_dout(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_dout),
    .if_empty_n(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_empty_n),
    .if_read(zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_ap_ready)
);

start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_confOgC start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_confOgC_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_din),
    .if_full_n(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_full_n),
    .if_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_start_write),
    .if_dout(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_empty_n),
    .if_read(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_ap_ready)
);

start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_confiPgM start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_confiPgM_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_din),
    .if_full_n(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_full_n),
    .if_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_start_write),
    .if_dout(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_dout),
    .if_empty_n(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_empty_n),
    .if_read(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_ap_ready)
);

start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0 start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_din),
    .if_full_n(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_full_n),
    .if_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_start_write),
    .if_dout(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_dout),
    .if_empty_n(start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_empty_n),
    .if_read(zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_ap_ready)
);

start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_confQgW start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_confQgW_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_din),
    .if_full_n(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_full_n),
    .if_write(zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_start_write),
    .if_dout(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_empty_n),
    .if_read(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_ap_ready)
);

start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_confiRg6 start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_confiRg6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_din),
    .if_full_n(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_full_n),
    .if_write(conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_start_write),
    .if_dout(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_dout),
    .if_empty_n(start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_empty_n),
    .if_read(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_ap_ready)
);

start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0 start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_din),
    .if_full_n(start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_full_n),
    .if_write(relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_start_write),
    .if_dout(start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_dout),
    .if_empty_n(start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_empty_n),
    .if_read(pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_ap_ready)
);

start_for_dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0 start_for_dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_din),
    .if_full_n(start_for_dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_full_n),
    .if_write(pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_start_write),
    .if_dout(start_for_dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_dout),
    .if_empty_n(start_for_dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_empty_n),
    .if_read(dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_ap_ready)
);

start_for_sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0 start_for_sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_din),
    .if_full_n(start_for_sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_full_n),
    .if_write(dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_start_write),
    .if_dout(start_for_sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_dout),
    .if_empty_n(start_for_sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_empty_n),
    .if_read(sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_ap_ready)
);

assign ap_done = sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_ap_done;

assign ap_idle = (zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_ap_idle & zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_ap_idle & zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_ap_idle & zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_ap_idle & zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_ap_idle & zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_ap_idle & sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_ap_idle & relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_ap_idle & relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_ap_idle & relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_ap_idle & relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_ap_idle & relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_ap_idle & relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_ap_idle & pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_ap_idle & pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_ap_idle & pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_ap_idle & dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_ap_idle & conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_ap_idle & conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_ap_idle & conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_ap_idle & conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_ap_idle & conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_ap_idle & conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_ap_idle);

assign ap_ready = zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_ap_done;

assign ap_sync_ready = zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_ap_ready;

assign conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_ap_continue = 1'b1;

assign conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_ap_start = start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_empty_n;

assign conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_ap_continue = 1'b1;

assign conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_ap_start = start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_empty_n;

assign conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_ap_continue = 1'b1;

assign conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_ap_start = start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_empty_n;

assign conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_ap_continue = 1'b1;

assign conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_ap_start = start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_empty_n;

assign conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_ap_continue = 1'b1;

assign conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_ap_start = start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_empty_n;

assign conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_ap_continue = 1'b1;

assign conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_ap_start = start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_empty_n;

assign dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_ap_continue = 1'b1;

assign dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_ap_start = start_for_dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_empty_n;

assign input_1_V_V_TREADY = zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_data_V_V_TREADY;

assign layer34_out_V_V_TDATA = sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_res_V_V_TDATA;

assign layer34_out_V_V_TVALID = sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_res_V_V_TVALID;

assign pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_ap_continue = 1'b1;

assign pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_ap_start = start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_empty_n;

assign pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_ap_continue = 1'b1;

assign pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_ap_start = start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_empty_n;

assign pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_ap_continue = 1'b1;

assign pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_ap_start = start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_empty_n;

assign relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_ap_continue = 1'b1;

assign relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_ap_start = start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_empty_n;

assign relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_ap_continue = 1'b1;

assign relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_ap_start = start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_empty_n;

assign relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_ap_continue = 1'b1;

assign relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_ap_start = start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_empty_n;

assign relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_ap_continue = 1'b1;

assign relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_ap_start = start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_empty_n;

assign relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_ap_continue = 1'b1;

assign relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_ap_start = start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_empty_n;

assign relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_ap_continue = 1'b1;

assign relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_ap_start = start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_empty_n;

assign sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_ap_continue = 1'b1;

assign sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_ap_start = start_for_sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_empty_n;

assign sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_start_full_n = 1'b1;

assign sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_start_write = 1'b0;

assign start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config12_U0_din = 1'b1;

assign start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config16_U0_din = 1'b1;

assign start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config21_U0_din = 1'b1;

assign start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config25_U0_din = 1'b1;

assign start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config3_U0_din = 1'b1;

assign start_for_conv_2d_cl_ss_ap_fixed_ap_fixed_18_8_5_3_0_config7_U0_din = 1'b1;

assign start_for_dense_ss_ap_fixed_ap_fixed_18_8_5_3_0_config31_U0_din = 1'b1;

assign start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config11_U0_din = 1'b1;

assign start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config20_U0_din = 1'b1;

assign start_for_pooling2d_cl_ss_ap_fixed_ap_fixed_config29_U0_din = 1'b1;

assign start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config10_U0_din = 1'b1;

assign start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config15_U0_din = 1'b1;

assign start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config19_U0_din = 1'b1;

assign start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config24_U0_din = 1'b1;

assign start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config28_U0_din = 1'b1;

assign start_for_relu_ss_ap_fixed_ap_fixed_18_8_5_3_0_relu_config6_U0_din = 1'b1;

assign start_for_sigmoid_ss_ap_fixed_ap_fixed_sigmoid_config34_U0_din = 1'b1;

assign start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_din = 1'b1;

assign start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_din = 1'b1;

assign start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_din = 1'b1;

assign start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_din = 1'b1;

assign start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_din = 1'b1;

assign zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_ap_continue = 1'b1;

assign zeropad2d_cl_ss_ap_fixed_ap_fixed_config35_U0_ap_start = ap_start;

assign zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_ap_continue = 1'b1;

assign zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_ap_start = start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config36_U0_empty_n;

assign zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_ap_continue = 1'b1;

assign zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_ap_start = start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config37_U0_empty_n;

assign zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_ap_continue = 1'b1;

assign zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_ap_start = start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config38_U0_empty_n;

assign zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_ap_continue = 1'b1;

assign zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_ap_start = start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config39_U0_empty_n;

assign zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_ap_continue = 1'b1;

assign zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_ap_start = start_for_zeropad2d_cl_ss_ap_fixed_ap_fixed_config40_U0_empty_n;

endmodule //myproject
